### ISSUE TITLE
Security problem

### ISSUE THREAD

**Issue by DSamaryan** [android-pay/s2ap-quickstart-android#2]
Is there a security problem to save ISSUER_ID in an android app?

**Comment by ncalteen** [comment]
Hello,

My apologies, this repository is being deprecated. Please refer to the following repositories going forward. If there is anything you would like assistance with, please feel free to submit an issue.

* [google-pay/android-quickstart](https://github.com/google-pay/android-quickstart)
* [google-pay/wallet-samples](https://github.com/google-pay/wallet-samples)
