### ISSUE TITLE
deprecated CreateWalletObjectsRequest 

### ISSUE THREAD

**Issue by LOG-TAG** [android-pay/s2ap-quickstart-android#5]
update needed since many methods are deprecated https://developers.google.com/android/reference/com/google/android/gms/wallet/CreateWalletObjectsRequest#newBuilder()

**Comment by ncalteen** [comment]
Hello,

My apologies, this repository is being deprecated. Please refer to the following repositories going forward. If there is anything you would like assistance with, please feel free to submit an issue.

* [google-pay/android-quickstart](https://github.com/google-pay/android-quickstart)
* [google-pay/wallet-samples](https://github.com/google-pay/wallet-samples)
