### ISSUE TITLE
Why is there no other pixel densities than the default?

### ISSUE THREAD

**Issue by danielmockaitis** [android-pay/s2ap-quickstart-android#6]
Is this repo no longer supported?

**Comment by ncalteen** [comment]
Hello,

My apologies, this repository is being deprecated. Please refer to the following repositories going forward. If there is anything you would like assistance with, please feel free to submit an issue.

* [google-pay/android-quickstart](https://github.com/google-pay/android-quickstart)
* [google-pay/wallet-samples](https://github.com/google-pay/wallet-samples)
