### ISSUE TITLE
Failed error code: -1

### ISSUE THREAD

**Issue by hardwayraja** [android-pay/s2ap-quickstart-android#7]
When i try to save to phone, I am getting an error message "failed error code:  -1"
Can anyone please tell why is it so

**Comment by Sheepwiz** [comment]
I'm experiencing the same issue currently but it seems like the last response in the follow open issue is the correct answer. More specifically it seems like you have to whitelist the app when testing which is something that isn't very clear in the documentation. 
https://github.com/google-pay/s2gp-quickstart-android/issues/4

**Comment by hardwayraja** [comment]
Hi ,
I have white listed the app and did the steps in the same way mentioned in official document. But still I am getting the same response "Failed errorcode: -1"
Can anyone provide the solution for it?

**Comment by shishirshettygit** [comment]
> Hi ,
> I have white listed the app and did the steps in the same way mentioned in official document. But still I am getting the same response "Failed errorcode: -1"
> Can anyone provide the solution for it?

@hardwayraja , even I am facing the same issue. Let me know if you made any progress. Thanks.

**Comment by chinalwb** [comment]
Same here! Any solutions?

**Comment by jyotigame** [comment]
any one got solution on the error ???

**Comment by jyotigame** [comment]
please post the solution if any one got solution...

**Comment by ncalteen** [comment]
Hello,

My apologies, this repository is being deprecated. Please refer to the following repositories going forward. If there is anything you would like assistance with, please feel free to submit an issue.

* [google-pay/android-quickstart](https://github.com/google-pay/android-quickstart)
* [google-pay/wallet-samples](https://github.com/google-pay/wallet-samples)
